### ISSUE TITLE
Panoramio規約対応

### ISSUE THREAD

**Issue by matsumo1001** [tnumata3632/RakuTabi#111]

**Comment by tnumata3632** [comment]
**Attribution Requirements**

Every photo displayed in your site should include Panoramio's name and our logo. The API provides photos in six possible versions: mini square, square, thumbnail, small, medium (default) and original. Each mini square-, square-, thumbnail- or small-size version of a photo must link to a medium or original sized version of the same photo. **Each medium or original sized version must link to the photo page on the Panoramio.com domain (for example, http://www.panoramio.com/photo/532693)**. The link should be under the image itself. No more than 50 instances of photos can be displayed on one single webpage.

Additionally, every time a medium or original photo is used, you must also **show the Panoramio logo directly under or directly next to the photo**, as well as **display "author: name", where "name" is linked to the author's Panoramio photos homepage (for example, http://www.panoramio.com/user/1429589)**. You must also **display the text "Photos provided by Panoramio are under the copyright of their owners"** under Panoramio photos.

> http://www.panoramio.com/api/data/api.html

**Comment by tnumata3632** [comment]
- [ ] Panoramio.com の画像ページにリンクさせる（やらない？）
- [ ] Panoramioのロゴを画像の隣に表示する（下の画像を使う予定）
- [x] "author: name" を表示し、著者者名から Panoramio の写真にリンクする
- [x] "Photos provided by Panoramio are under the copyright of their owners" を表示する

**Comment by tnumata3632** [comment]
http://www.panoramio.com/img/panoramio-marker.png
