### ISSUE TITLE
ハックチャレンジ対応

### ISSUE THREAD

**Issue by tnumata3632** [tnumata3632/RakuTabi#119]
> アプリケーション登録期限を経過すると、Salesforceのテクニカルエキスパートを中心とした審査チームにより、アプリケーションの審査が行われます。 
> 
> アプリケーションの審査には当然コード自体のレビューが含まれますが、初回に提出されたアプリケーション概要、Gitリポジトリ内のReadme.mdファイルに記載されている内容も大きく審査に影響を与えます。 アプリケーションがReadme.mdに記載されているインストラクションに基づいて、審査員が簡単にビルド、実行できることを確認しておいて下さい。 また説明用にスライドやデモ動画などを用意してReadme.md内で紹介するというのも、審査員にそのプログラムの価値や利用手順を確実に伝えるのに非常に有効です。

**Comment by sshamoto** [comment]
- [x] 動画作成　→　落
- [x] ハッシュタグ画像作成（画像ある時用、ない時用）、デザイン　→　浅
- [x] ハッシュタグ画像実装　→　松
- [x] Readme修正　→　落
