### ISSUE TITLE
Google Analytics 設置

### ISSUE THREAD

**Issue by tnumata3632** [tnumata3632/RakuTabi#132]
PPC とか リスティング とか
将来するかもしれないので それまでに。

**Comment by sshamoto** [comment]
- [x] メアド作成（admin、hello）→落
- [ ] Google Analytics設置→沼

**Comment by ochiait** [comment]
##(参考)[初心者向けGoogleアナリティクス活用法](http://www.slideshare.net/nanaehibino9/google-2014127)
