### ISSUE TITLE
ユーザーは、提示された2枚の画像から選択し、自分の好みを回答できる

### ISSUE THREAD

**Issue by sshamoto** [tnumata3632/RakuTabi#15]
棚卸する時に説明します。以下自分用メモ。
- プロファイル登録・検索のもっと軽いバージョン
- ログイン不要、好みの登録もしない（DBに入れておかない）
- 写真の2択×3回ぐらい質問して、その時どんなところに行きたい気分か、どんなシチュエーションでの旅行かを簡単に答えてもらう
  - 「自然の写真」vs「街の写真」とか
  - 「ぼっちの写真」vs「みんなでわいわいしてる写真」とか
  - 「高級っぽい写真」vs「チープな写真」とか
  - 結構ふざけた質問も出してもいいかも
- 写真にはキーワードを紐づけておいて、APIたたく時にパラメータにセット（「癒し」、「太陽」、「赤」とかでフリーワード検索できるもよう）
- 毎回ランダムに質問して、2度と同じレコメンドをださないセレンディピティと、予想外のレコメンドがでるサプライズ、みたいな

---

このPBIでは、画像選択ページを用意して、そこで画像を選ぶところまで。
2枚の画像はそれぞれリンクになっており、リンク先は同一の検索結果画面。
そのため選択結果によらず同じ結果が出るところまででok。

詳細タスク：
- [x] 画像選択するためのページを1つ追加
- [x] ページ遷移を、POSTからGETに変更
- [x] 2枚の画像から選択する部分のUIとデザイン(HTML/CSS)

**Comment by matsumo1001** [comment]
sample by asaki-san
![sample](https://cloud.githubusercontent.com/assets/920462/4600473/4831b3da-50d5-11e4-862c-7d62a4e357f3.png)

**Comment by sshamoto** [comment]
ありがとうございます。
私のイメージを共有するために作ったものなので、今日のプランニングでの方向性に合わせて自由に修正くださいませ。

**Comment by matsumo1001** [comment]
落合さん開発内容
（修正）app/view/top/index.html.erb
　　→　ボタンを押したときの遷移先を/tourから/selectionに変更
（新規）app/view/tour/select.html.erb
　　→　画像を二つ並べて選択できる画面を作成。
　　　　画像がlinkになっておりクリックすると次のようなURLが呼ばれるイメージ
　　　　/tour?imgid=xxx
　　　　imgidの値でどちらの画像がクリックされたかcontroller側で判別する。
