### ISSUE TITLE
ユーザは気に入った目的地に関する写真がみれる

### ISSUE THREAD

**Issue by sshamoto** [tnumata3632/RakuTabi#16]
- [x] 写真 [松]

**Comment by sshamoto** [comment]
地名をキーに、instagramから写真をひっぱってくるとか。
インスタの写真なら、ある程度クオリティが保たれるし（なんならabroadの写真よりベター）、なにより情報が新鮮。

**Comment by sshamoto** [comment]
すでに話にあがった現地の天気情報。

【参考】情報古いかもしれないけど、天気APIまとめ
http://hello-apis.blogspot.jp/2013/03/webapi.html

**Comment by sshamoto** [comment]
あと、おおむね英語になっちゃうけど、tumblrとかもいいかも。雰囲気は伝わる。

**Comment by tnumata3632** [comment]
客観的な情報源として、Wikipedia。
あまり面白みはないので載せるとしても概要(+写真)ぐらいか。
APIで取得できる。
http://www.mediawiki.org/wiki/API:Main_page/ja

**Comment by tnumata3632** [comment]
> 写真 [松 or 沼]
> 参考
> http://www.gramfeed.com/instagram/map#/37.7749,-122.4194/1000/

**Comment by sshamoto** [comment]
モーダル化は #114 とカバーしているので、こっちはクローズします。
