### ISSUE TITLE
行き先が重複しているツアー情報を除外した検索結果を照会できる

### ISSUE THREAD

**Issue by sshamoto** [tnumata3632/RakuTabi#37]
- [x] サブタスク [松]

**Comment by matsumo1001** [comment]
当issueの仕様は下記の通りとした。
1. フリーワードマッチ順で先頭100件取得
2. クエリー条件にマッチする、検索結果の全件数が100件以上の場合
   1. もう一度クエリを実行し、最後の100件を取得、先頭100件とマージする（先頭100件と重複しないように最後の100件を取得）
3. 上記で取得したツアーについて、宿泊地要約（すべての宿泊地の文字列city要素のnameを接続した文字列）が重複しているツアーを除外
4. ランダムに10件を返す

**Comment by matsumo1001** [comment]
キーワードによっては検索結果の全件数が数千件となって、100件ずつ全件取得するのが、現実的ではないので最初100件と最後100件をとるようにしてみました。キーワードマッチ順なので、最後100件を取るとちょっと意外なツアーとかでるかなと思いそうしています。あまりにも違和感ある場合は次回以降で見直しというこで。

**Comment by matsumo1001** [comment]
あと、現状、仕様の4でランダムに10件返していますが、ページングを実装する場合は、3.の結果について位置を指定して返せるようにする想定です。

**Comment by matsumo1001** [comment]
あと、経度・緯度情報がないツアーがあり、マップに表示できないので除外しています。
