### ISSUE TITLE
検索結果画面で、ツアー情報と地図がインタラクティブに確認できる

### ISSUE THREAD

**Issue by sshamoto** [tnumata3632/RakuTabi#41]
- [x] アクティブなピンと、そうじゃないピンの画像を用意する [浅]
- [x] スライドショーをいじると、地図が連動する [沼]
- [x] 地図をいじると、スライドショーが連動する [松]

**Comment by sshamoto** [comment]
flexslider 2参照。

**Comment by tnumata3632** [comment]
FlexSlider 2
http://flexslider.woothemes.com/index.html
https://github.com/woothemes/FlexSlider

参考資料
http://on-ze.com/archives/409
http://stackoverflow.com/questions/11859102/control-flexslider-from-outside-element
