### ISSUE TITLE
Mapの表示改善

### ISSUE THREAD

**Issue by tnumata3632** [tnumata3632/RakuTabi#47]
- [x] デフォルト縮尺を1段階ズームアップ（世界が1周分表示されるように)
- [x] マップ領域の縦サイズをもう少し拡大
- [x] マーカー表示するときの視覚効果を設定できたはず

**Comment by sshamoto** [comment]
レポートの現実逃避に地図いじってたのですが。
地図を縦280pxにするとバランス的にはいいのですが、かんじんの地図が上下微妙に切れてしまうという...。悩ましいですね、これ。

![screenshot](https://cloud.githubusercontent.com/assets/5884140/4781124/0e531f7a-5c8b-11e4-8d1a-798038713e70.png)

**Comment by tnumata3632** [comment]
縦320pxにトライ
![image](https://cloud.githubusercontent.com/assets/8116426/4812948/71be54a4-5ec4-11e4-9428-da2c7f513b03.png)

**Comment by tnumata3632** [comment]
・マーカー表示するときの視覚効果 → 500msecずつずらしてdrop表示
・ズームボタンを右上に変更（左上だと地図を邪魔してたので）
