### ISSUE TITLE
気になったツアーの詳細情報がみれる

### ISSUE THREAD

**Issue by tnumata3632** [tnumata3632/RakuTabi#49]
- [x] 空の詳細画面に遷移できるようにする
  - [x] 新規の空ページを作る
  - [x] ツアー画像から、空ページへのリンクをはる(URL固定でok)
  - [x] 空ページのデザインを何かしらつくる Comming Soonとか
- [x] 選択したツアーの詳細情報を出力する
  - [x] URLのパラメータにツアーIDを載せる
  - [x] 詳細画面で、パラメータを取得して、ツアーIDを表示する
  - [x] ツアーIDを元にAPIを呼び出して詳細情報取得し表示する

**Comment by matsumo1001** [comment]
第一段階でつくるもの
- /app/views/tour/search.html.erb（画像をリンクに修正）
- /config/routes.rb（ルーティング情報追加）
- /app/controllers/tour_controller.rb（ルーティングに合わせてメソッド追加。最初は空でよい）
- /app/views/tour/(controllerのメソッド名).html.erb（詳細情報の表示画面）
