### ISSUE TITLE
オフラインでターゲットユーザにテストしてもらう

### ISSUE THREAD

**Issue by sshamoto** [tnumata3632/RakuTabi#58]
- [x] やり方検討
- [ ] オフラインで知人にテストしてもらう [各自]

**Comment by imagire** [comment]
いくつか参考になる場所があると思いますが、たとえば、このブログを見てみてください
http://directorblog.jp/archives/50758263.html

**Comment by ochiait** [comment]
こういったグループにお願いして、評価を聞いてみるのもいいかと思いました。

旅行好きによる旅行好きのためのグループ
https://www.facebook.com/groups/202808359912090/?fref=ts

TravelBook～海外好きが集まるFacebookグループ～
https://www.facebook.com/groups/182333365229353/?fref=ts
