### ISSUE TITLE
【締切12/18(木)】enPiTシンポジウム資料作成

### ISSUE THREAD

**Issue by tnumata3632** [tnumata3632/RakuTabi#93]
> みなさま、
> 
> 下記の通り、来年の１月２７日にenPiTシンポジウムが開催されます。
> http://www.enpit.jp/event/2014/11/enpit-3-7446.html
> 平日で名古屋開催なので参加するのは難しいとは思いますが…
> 
> つきましては、添付の資料を参考にみなさんのプロダクトの説明を一枚でまとめてください。
> 時間が少なくて、恐縮なのですが、12/18(木)まで提出いただくようにおねがいします。
> 
> よ

**Comment by sshamoto** [comment]
永瀬先生のメールだと、締め切りは金曜日。

---

1-2. シンポジウム発表用ポスター作成 12/19(金) 締切
参考までに昨年のものを添付します。
A4横1枚のイメージで、最低限プロダクト名、プロダクトURL、プロダクトイメージを含んでパッケージしてください。
提出フォーマットはPDFでお願いします。このML宛に投げてください。
下記今後のイベントで使用される予定です。
