### ISSUE TITLE
【締切12/7(日)】enPiT PBL発表会のチラシに掲載する情報

### ISSUE THREAD

**Issue by tnumata3632** [tnumata3632/RakuTabi#94]
> 来年2/21(土)のenPiT PBL発表会のチラシに掲載する情報を集めています。
> 
> 各チームから、以下の3点について返信をください。
> 1. チーム名
> 2. プロダクト名
> 3. 概要（20文字程度）
> 
> 締切は12/7(日)まで。このML宛で結構です。
> よろしくお願いします。

**Comment by sshamoto** [comment]
チーム名とプロダクト名はいいとして、概要ですよね。
サイトのトップページにある「思いつかないような場所へ行ける、旅行目的地レコメンドサービス」(30文字)を縮めればいいでしょうか？
